# Generated by Django 6.0.6 on 2026-06-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrekkingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permit_type', models.CharField(choices=[('TIMS', 'TIMS'), ('ANNAPURNA', 'Annapurna National Park'), ('EVEREST', 'Everest National Park'), ('LANGTANG', 'Langtang National Park')], db_index=True, max_length=32)),
                ('applied_date', models.DateField()),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='APPLIED', max_length=16)),
                ('documents', models.JSONField(blank=True, help_text='Uploaded document metadata (paths, checksums, types)', null=True)),
                ('route_bounds', models.JSONField(blank=True, help_text='GeoJSON bounding box or path for the trek', null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trekking permit',
                'verbose_name_plural': 'trekking permits',
            },
        ),
    ]
