# Generated by Django 6.0.6 on 2026-06-23 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_remote', models.BooleanField(default=False, help_text='Remote regions carry a pricing premium (Dolpo, Mustang, ...).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('festival_name', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(choices=[('Religious', 'Religious'), ('Cultural', 'Cultural'), ('Seasonal', 'Seasonal')], db_index=True, max_length=16)),
                ('start_month', models.PositiveSmallIntegerField(default=1)),
                ('duration_days', models.PositiveSmallIntegerField(default=1)),
                ('region', models.CharField(blank=True, help_text='Province/area name (free text)', max_length=128)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('badge_eligible', models.BooleanField(default=False)),
                ('significance', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=8)),
                ('badge_points', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['start_month', 'festival_name'],
                'indexes': [models.Index(fields=['year', 'start_month'], name='catalog_cul_year_912135_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuideRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, help_text='Dataset guide_id, e.g. GDE00001', max_length=16, unique=True)),
                ('guide_code', models.CharField(db_index=True, help_text='Public code shown in-app', max_length=64)),
                ('ntb_license_no', models.CharField(db_index=True, max_length=64)),
                ('certification', models.CharField(choices=[('IFMGA Mountain Guide', 'IFMGA Mountain Guide'), ('Government Trekking Guide', 'Government Trekking Guide'), ('NATHM Trekking Guide', 'NATHM Trekking Guide'), ('NATHM Tour Guide', 'NATHM Tour Guide'), ('City Guide (Licensed)', 'City Guide (Licensed)'), ('Cultural Specialist', 'Cultural Specialist'), ('Bird-watching Specialist', 'Bird-watching Specialist'), ('Adventure Sports Guide', 'Adventure Sports Guide')], db_index=True, max_length=64)),
                ('languages_spoken', models.CharField(blank=True, max_length=255)),
                ('regions_covered', models.CharField(blank=True, help_text='Comma-separated region names', max_length=512)),
                ('years_experience', models.FloatField(default=0)),
                ('average_rating', models.FloatField(db_index=True, default=0)),
                ('total_trips_completed', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Pending Renewal', 'Pending Renewal'), ('Expired', 'Expired')], db_index=True, default='Verified', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('linked_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_entry', to='authentication.guideprofile')),
            ],
            options={
                'verbose_name': 'guide registry entry',
                'verbose_name_plural': 'guide registry',
                'ordering': ['-average_rating'],
                'indexes': [models.Index(fields=['certification', 'average_rating'], name='catalog_gui_certifi_1998d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricingBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('service_type', models.CharField(db_index=True, max_length=64)),
                ('season', models.CharField(db_index=True, help_text='Peak (Spring) / Off (Winter) / ...', max_length=32)),
                ('fair_price_npr', models.PositiveIntegerField()),
                ('min_fair_npr', models.PositiveIntegerField()),
                ('max_fair_npr', models.PositiveIntegerField()),
                ('currency', models.CharField(default='NPR', max_length=8)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('source_type', models.CharField(blank=True, max_length=32)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='benchmarks', to='catalog.region')),
            ],
            options={
                'ordering': ['service_type', 'region__name'],
                'indexes': [models.Index(fields=['service_type', 'region', 'season'], name='catalog_pri_service_e60aa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrekkingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, help_text='Dataset route_id, e.g. RTE0001', max_length=16, unique=True)),
                ('route_name', models.CharField(db_index=True, max_length=255)),
                ('permits_required', models.CharField(blank=True, help_text='Comma-separated permit names', max_length=255)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard'), ('Very Hard', 'Very Hard')], db_index=True, max_length=16)),
                ('difficulty_level', models.PositiveSmallIntegerField(default=1, help_text='1=Easy .. 4=Very Hard')),
                ('max_altitude_m', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveSmallIntegerField(default=1)),
                ('best_seasons', models.CharField(blank=True, max_length=64)),
                ('seasonal_closure_months', models.CharField(blank=True, max_length=64)),
                ('badge_points', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Moderation gate')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='catalog.region')),
            ],
            options={
                'ordering': ['route_name'],
                'indexes': [models.Index(fields=['difficulty_level'], name='catalog_tre_difficu_794d4b_idx'), models.Index(fields=['region', 'difficulty_level'], name='catalog_tre_region__4b6fb3_idx')],
            },
        ),
    ]
