# Generated by Django 6.0.6 on 2026-06-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BOOKING', 'Booking'), ('PAYMENT', 'Payment'), ('PERMIT', 'Permit'), ('REVIEW', 'Review'), ('SCAM', 'Scam alert'), ('GAMIFICATION', 'Gamification'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, help_text='Structured payload for deep-linking in the apps', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
    ]
