# Generated by Django 6.0.6 on 2026-06-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('Cultural', 'Cultural'), ('Adventure', 'Adventure'), ('Explorer', 'Explorer'), ('Safety', 'Safety')], db_index=True, max_length=16)),
                ('points', models.PositiveIntegerField(default=0)),
                ('trigger_event', models.CharField(blank=True, help_text='What earns this badge', max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('trigger_event', models.CharField(blank=True, max_length=128)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='gamificatio_user_id_45ed80_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'badge'), name='uniq_badge_per_user')],
            },
        ),
    ]
