# Generated by Django 6.0.6 on 2026-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('VIEW', 'View'), ('CLICK', 'Click'), ('SEARCH', 'Search'), ('WISHLIST', 'Wishlist'), ('BOOK', 'Book'), ('RATE', 'Rate'), ('SHARE', 'Share'), ('COMPLETE', 'Complete'), ('SCAM_CHECK', 'Scam check')], db_index=True, max_length=16)),
                ('item_type', models.CharField(blank=True, help_text='Route / Guide / Event / ...', max_length=16)),
                ('item_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source', models.CharField(blank=True, help_text='In-app surface, e.g. Recommendation Feed', max_length=64)),
                ('device', models.CharField(blank=True, max_length=16)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
