# Generated by Django 6.0.6 on 2026-06-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['event_type', '-created_at'], name='analytics_u_event_t_934a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['item_type', 'item_id'], name='analytics_u_item_ty_c5c594_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['actor', '-created_at'], name='analytics_u_actor_i_7798a4_idx'),
        ),
    ]
