# Generated by Django 6.0.6 on 2026-06-23 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(db_index=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('season', models.CharField(blank=True, max_length=32)),
                ('quoted_price_npr', models.PositiveIntegerField()),
                ('benchmark_price_npr', models.PositiveIntegerField(blank=True, null=True)),
                ('overcharge_ratio', models.FloatField(blank=True, null=True)),
                ('is_likely_scam', models.BooleanField(default=False)),
                ('source', models.CharField(default='benchmark', help_text='benchmark | ml', max_length=16)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(db_index=True, max_length=64)),
                ('season', models.CharField(blank=True, max_length=32)),
                ('quoted_price_npr', models.PositiveIntegerField()),
                ('benchmark_price_npr', models.PositiveIntegerField(help_text='Fair benchmark resolved at submission')),
                ('overcharge_ratio', models.FloatField(db_index=True)),
                ('scam_severity', models.CharField(choices=[('Fair', 'Fair'), ('Mild Overcharge', 'Mild Overcharge'), ('Moderate Overcharge', 'Moderate Overcharge'), ('Severe Overcharge', 'Severe Overcharge'), ('Likely Scam', 'Likely Scam')], db_index=True, max_length=24)),
                ('was_flagged_by_app', models.BooleanField(db_index=True, default=False)),
                ('ml_scam_probability', models.FloatField(blank=True, help_text='Score from the analytics-engine, if available', null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('DISMISSED', 'Dismissed')], db_index=True, default='SUBMITTED', max_length=12)),
                ('verified_by_moderator', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scam_reports', to='catalog.region')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scam_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_type', 'region'], name='trust_scamr_service_50db82_idx')],
            },
        ),
    ]
