# Generated by Django 6.0.6 on 2026-06-23 16:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Display title for the tour package', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price in platform currency', max_digits=10)),
                ('duration_days', models.PositiveSmallIntegerField(default=1, help_text='Typical duration in days')),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Max number of tourists allowed')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'tour package',
                'verbose_name_plural': 'tour packages',
            },
        ),
        migrations.CreateModel(
            name='BookingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=16)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('booking_reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.trekkingroute')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('tour_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.tourpackage')),
            ],
            options={
                'verbose_name': 'booking session',
                'verbose_name_plural': 'booking sessions',
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_index', models.PositiveIntegerField(help_text='Day number within the tour, starting from 1')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.JSONField(blank=True, help_text='Geo location or place metadata (GeoJSON)', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='bookings.bookingsession')),
            ],
            options={
                'verbose_name': 'itinerary item',
                'verbose_name_plural': 'itinerary items',
                'ordering': ['booking', 'day_index'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingsession',
            index=models.Index(fields=['status'], name='bookings_bo_status_bc2d2d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsession',
            index=models.Index(fields=['tourist'], name='bookings_bo_tourist_e87d71_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingsession',
            index=models.Index(fields=['assigned_guide'], name='bookings_bo_assigne_5c3452_idx'),
        ),
    ]
